services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    hostname: db
    expose:
      - 5432
    volumes:
      - my_data:/var/lib/postgresql/data
    ports:
      -  "5432:5432"
    environment:
      POSTGRES_USER:  ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  adminer:
    image: adminer
    hostname: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  my_data:
