services:
    db:
      image: postgres:latest
      container_name: db
      volumes:
        - dbidata:/var/lib/postgresql/data
      ports:
        -  "5432"
      environment:
        POSTGRES_USER:  ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
volumes:
  db-data:
